### ISSUE TITLE
Advice?

### ISSUE THREAD

**Issue by 20chix** [AlessioTonioni/Autonomous-Flight-ROS#10]
Hi Alessio

I was wondering if I can please have your advice on a project I'm working on for my university, since I can see you are really experienced in ROS and drone. 

I have an indoor system, 4 physical waypoints and one anchor(master) attached to a raspberry pi , which is then placed on top of a drone(ardrone2.0). This anchor gets all the coordinates(xyz) from all the waypoints on the ground. So I don't have any maps or obstacle detection system or slam. 

I was wondering what would be your approach on telling the drone to go from xyz(drone position) to xyz(waypoint)? All ros packages seem to require slam or other unnecessary packages.

Thanks in advance.

**Comment by AlessioTonioni** [comment]
Send me an email: alessio.tonioni@unibo.it
