### ISSUE TITLE
nothing appear with $rostopic echo cmd_vel

### ISSUE THREAD

**Issue by ghost** [AlessioTonioni/Autonomous-Flight-ROS#2]
Hi,
i was trying to testing this project. But when i enter $ $rostopic echo cmd_vel,nothing appear.
Any body know why nothing appear? 
I am sure i have public cmd_vel.

**Comment by AlessioTonioni** [comment]
I think I will need more info to address your problem.
Can you describe your set up and what are you trying to do?
