### ISSUE TITLE
How do you take off?

### ISSUE THREAD

**Issue by 20chix** [AlessioTonioni/Autonomous-Flight-ROS#9]
Hi,

I know is been a while, but I was wondering if you know how to take off  the drone?

These are my topics, after launching all your sh files. 

![screenshot from 2018-12-20 22-09-08](https://user-images.githubusercontent.com/15612171/50313738-44630b00-04a4-11e9-8491-877cd827f9b3.png)

By doing few searches online I was recommended to enable motors of hector to true but i can't see the topic /enable-motors

I also tried to run your teleop from keyboard but nothing happens, I can see it appearing in /cmd_vel nothing in gazebo or rviz.

Also I'm guessing the planned path will only display in gazebo if the drone is taking off?

PS: I'm using kinetic, nothing much changed from groovy or indigo. So I think versions shouldn't be a problem

Thanks in advance

**Comment by AlessioTonioni** [comment]
Hi, 
as far as I remember when I used the package the drone was already flying after being spawned, so, unfortunately, I don't have any advice on how to make it take off.

**Comment by 20chix** [comment]
Sorry for late response, but thanks  for your response anyway.

I'm developing autonomous indoor drone, similar to yours but with real waypoints. If you want and curious I can add to the repo.
